### ISSUE TITLE
Beeper half-on at startup when nothing connected

### ISSUE THREAD

**Issue by igough** [filipmu/Marlin-Mackerel#1]
To test new hardware, I connected the MEGA, RAMPS and LCD up and uploaded the firmware. Just after the splash screen, the beeper started a sickly screech. I think this is supposed to be the alarm for the min temperature in order to detect an bad thermistor. The problem is that the beeper is only half on because at this point, the BEEPER has not been set to output. Maybe it is set to INPUT_PULLUP which partially turns on the BEEPER?

Add this to the end of setup()

  #if BEEPER > 0
    SET_OUTPUT(BEEPER);
  #endif

and the beeper will clearly sing out its displeasure at having no thermistor attached.

**Comment by filipmu** [comment]
Thanks for the suggestion.  I will add it to the code.  Yes, the beeper will sound at powerup without a thermistor attached.

From: igough 
Sent: Sunday, September 14, 2014 9:42 AM
To: filipmu/Marlin-Mackerel 
Subject: [Marlin-Mackerel] Beeper half-on at startup when nothing connected (#1)

To test new hardware, I connected the MEGA, RAMPS and LCD up and uploaded the firmware. Just after the splash screen, the beeper started a sickly screech. I think this is supposed to be the alarm for the min temperature in order to detect an bad thermistor. The problem is that the beeper is only half on because at this point, the BEEPER has not been set to output. Maybe it is set to INPUT_PULLUP which partially turns on the BEEPER?

Add this to the end of setup()

#if BEEPER > 0
SET_OUTPUT(BEEPER);
#endif

and the beeper will clearly sing out its displeasure at having no thermistor attached.

**Comment by filipmu** [comment]
I added this suggestion.
